---
# tasks file for std-packages
- name: Install required system packages
  ansible.builtin.package:
    name: "{{ packages[ansible_os_family | lower] }}"
    state: latest # noqa package-latest
    update_cache: true
