---
# tasks file for disable-ipv6
- name: Check if ipv6 settings are disabled in /etc/sysctl.conf
  ansible.builtin.lineinfile:
    path: "/etc/sysctl.conf"
    state: present
    line: "{{ item }}"
  with_items:
    - "net.ipv6.conf.all.disable_ipv6=1"
    - "net.ipv6.conf.default.disable_ipv6=1"
    - "net.ipv6.conf.lo.disable_ipv6=1"

- name: Apply ipv6 disabled configuration
  ansible.builtin.shell: sysctl -p
