---
# remote_user: sacha
user:
  name: sacha
  ID: 501
  shell: /bin/zsh
  groups:
    - users
config_dirs:
  - { dir: ".config", mode: "0750" }
  - { dir: ".ssh", mode: "0700" }
  - { dir: ".vim", mode: "0750" }
  - { dir: ".vim/autoload", mode: "0750" }
  - { dir: ".vim/bundle", mode: "0750" }
config_files:
  - {
      src: "~/.config/telegram-send.conf",
      dest: "$HOME/.config/telegram-send.conf",
      mode: "0600",
    }
  - { src: "../files/ssh_config", dest: "$HOME/.ssh/config", mode: "0600" }
  - { src: "~/.ssh/id_rsa_github2", dest: "$HOME/.ssh/id_rsa_github2", mode: "0600" }
  - { src: "~/.ssh/known_hosts", dest: "$HOME/.ssh/known_hosts", mode: "0600" }
  # - {src: "../files/.gitconfig", dest: "$HOME/.gitconfig", mode: "0600" }
  - { src: "~/.ssh/authorized_keys", dest: "$HOME/.ssh/authorized_keys", mode: "0600" }
  - { src: "~/.vim/autoload", dest: "$HOME/.vim/", mode: "0600" }

copy_local_key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
packages:
  debian:
    - btop
    - curl
    - etckeeper
    - file
    - fonts-powerline
    - git
    - htop
    - neofetch
    - npm
    - python3-pip
    - smartmontools
    - speedtest-cli
    - sudo
    - tmux
    - vim
    - yamllint
    - yarn
    - zsh
  alpine:
    - curl
    - etckeeper
    - file
    - git
    - htop
    - neofetch
    - npm
    - py3-pip
    - smartmontools
    - speedtest-cli
    - sudo
    - tmux
    - vim
    - yamllint
    - yarn
  redhat:
    - curl
    - etckeeper
    - file
    - powerline-fonts
    - git
    - htop
    - neofetch
    - python3-pip
    - smartmontools
    # - speedtest-cli
    - sudo
    - tmux
    - vim
    - yamllint
    - zsh
time_zone: America/Toronto
locale_name: en_US.UTF-8
dotfiles: "/usr/bin/git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME"
remove_files:
  - .aliases
  - .bashrc
  - .gitconfig
  - .gvimrc
  - .minttyrc
  - .profile
  - .tmux.conf
#  - .vim
  - .vimrc
  - .xscreensaver
  - .zshrc
zsh_repo: "https://github.com/ohmyzsh/ohmyzsh.git"
