---
# remote_user: sacha
user:
  name: sacha
  ID: 501
  shell: /bin/zsh
  groups:
    - users
config_files:
  - {
      src: "telegram-send.conf",
      dest: "$HOME/.config/telegram-send.conf",
      mode: "0600",
    }
  - { src: "ssh_config", dest: "$HOME/.ssh/config", mode: "0600" }
  - { src: "id_rsa_github2", dest: "$HOME/.ssh/id_rsa_github2", mode: "0600" }
  - {
      src: "../files/known_hosts",
      dest: "$HOME/.ssh/known_hosts",
      mode: "0600",
    }
  # - {src: "../files/.gitconfig", dest: "$HOME/.gitconfig", mode: "0600"}
  - {
      src: "../files/authorized_keys",
      dest: "$HOME/.ssh/authorized_keys",
      mode: "0600",
    }

# copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa_github.pub') }}"
copy_local_key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
# copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa_github') }}"
packages:
  debian:
    - curl
    - etckeeper
    - file
    - fonts-powerline
    - git
    - htop
    - neofetch
    - python3-pip
    - smartmontools
    - speedtest-cli
    - sudo
    - tmux
    - vim
    - yamllint
    - zsh
  alpine:
    - curl
    - etckeeper
    - file
    - git
    - htop
    - neofetch
    - py3-pip
    - smartmontools
    - speedtest-cli
    - sudo
    - tmux
    - vim
    - yamllint
  redhat:
    - curl
    - etckeeper
    - file
    - powerline-fonts
    - git
    - htop
    - neofetch
    - python3-pip
    - smartmontools
    # - speedtest-cli
    - sudo
    - tmux
    - vim
    - yamllint
    - zsh
time_zone: America/Toronto
dotfiles: "/usr/bin/git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME"
remove_files:
  - .aliases
  - .bashrc
  - .gitconfig
  - .gvimrc
  - .minttyrc
  - .profile
  - .tmux.conf
  - .vim
  - .vimrc
  - .xscreensaver
  - .zshrc
zsh_repo: "https://github.com/ohmyzsh/ohmyzsh.git"
