- name: "Remove EXTERNALLY_MANAGED python config file on bookworm."
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/usr/lib/python3/EXTERNALLY-MANAGED"
    - "/usr/lib/python3.11/EXTERNALLY-MANAGED"
    - "/usr/lib/python3.12/EXTERNALLY-MANAGED"

      #  - name: "Install telegram-send"
  # ansible.builtin.package:
    # name: telegram-send
- name: "Install telegram."
  ansible.builtin.pip:
    name: telegram-send
- name: "Install pushbullet."
  ansible.builtin.pip:
    name: pushbullet-cli
