---
- name: "Asterisk and FreePBX playbook"
  hosts: hawk
  become: true
  tasks:
    - name: Install docker container
      community.docker.docker_container:
        restart: true
        restart_policy: always
        name: asterisk
        image: crazyquark/freepbx:15
        pull: true
        ports:
          - '80:80'
