- name: Update cache and upgrade all installed packages
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes
    autoremove: yes
    clean: yes
    cache_valid_time: 86400 #one day
  register: upgrade_output
- name: Update output
  debug:
    msg: "{{ upgrade_output }}"


