- name: Ensure the locale exists
  community.general.locale_gen:
    name: "{{ locale_name }}"
    state: present
# - name: set as default locale
#  command: localectl set-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
