---
- hosts: trumpet
  become: true
  tasks:
    - name: Copy dragon motd
      copy:
        src: "../files/dragon.motd"
        dest: /etc/motd
        owner: root
        group: root
        mode: "0644"
