---
- name: Apply my home settings and config files.
  become: true
  become_user: "{{ user.name }}"
  block:
    - name: Ensure HOME/.config exists
      ansible.builtin.file:
        path: $HOME/.config
        state: directory
        owner: "{{ user.name }}"
        group: users
        mode: "0700"
        # changed_when: false
    - name: Copy $HOME files not under version control
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      loop: "{{ config_files }}"
      changed_when: false
    - name: Clone oh-my-zsh
      ansible.builtin.git:
        repo: "{{ zsh_repo }}"
        # "https://github.com/ohmyzsh/ohmyzsh.git"
        dest: $HOME/.oh-my-zsh
        update: true
        force: true
    - name: Add zsh-autosuggestions to oh-my-zsh customizations
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-autosuggestions"
        dest: $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    - name: Add zsh-syntax-highlighting to oh-my-zsh customizations
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-syntax-highlighting"
        dest: $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    - name: Clone my scripts
      ansible.builtin.git:
        repo: "git@github.com:sachapan/scripts.git"
        # version: main
        update: true
        force: true
        dest: $HOME/bin
      changed_when: false
    - name: Clone my dotfiles from git - First purge clone
      ansible.builtin.file:
        path: $HOME/.dotfiles.git
        state: absent
    - name: Clone my dotfiles into a bare repo
      ansible.builtin.git:
        repo: https://github.com/sachapan/dotfiles.git
        dest: "$HOME/.dotfiles.git"
        version: main
        bare: true
        clone: true
        update: true
        force: true
    # - name: Don't show untracked files in this repo
    #  ansible.builtin.command: "{
    #    { dotfiles }} config --local status.showUntrackedFiles no"
    - name: Copy my git config for dotfiles.
      ansible.builtin.copy:
        src: "dotfiles.config"
        dest: "$HOME/.dotfiles.git/config"
        mode: "0600"
    - name: Remove default dotfiles
      ansible.builtin.file:
        path: "$HOME/{{ item }}"
        state: absent
      loop: "{{ remove_files }}"
    - name: Drop in my preferred dotfiles from git
      ansible.builtin.command: "{{ dotfiles }} checkout -f"
      changed_when: false
