---
- name: "Remove EXTERNALLY_MANAGED python config file on bookworm."
  ansible.builtin.file:
    path: "/usr/lib/python3.11/EXTERNALLY-MANAGED"
    state: absent
- name: "Install telegram."
  ansible.builtin.pip:
    name: telegram-send
- name: "Install pushbullet."
  ansible.builtin.pip:
    name: pushbullet-cli
