---
- hosts: alpine
  become: yes
    #become_user: root
    #become_method: sudo
  tasks:
    - name: update package cache and install all updates
      ansible.builtin.apk:
        update_cache: yes
        upgrade: true
        state: "latest"
