---
- name: Install qemu agent package
  ansible.builtin.package:
    # name: "{{ qemu_[ ansible_os_family | lower ] }}"
    name: qemu-guest-agent
    state: latest
    update_cache: true
- name: Start qemu-guest-agent service
  ansible.builtin.service:
    name: qemu-guest-agent
    state: started
    enabled: true
