---
- name: Set vim as default EDITOR for root
  ansible.builtin.lineinfile:
    path: "/root/.bashrc"
    state: present
    line: 'export EDITOR=vim'
- name: Add alias to nobc
  ansible.builtin.lineinfile:
    path: "/root/.bashrc"
    state: present
    line: 'alias nobc=~sacha/bin/nobc'
