---
- name: Ensure /root/.bashrc exists
  ansible.builtin.file:
    path: /root/.bashrc
    state: touch
    mode: '0500'
- name: Set vim as default EDITOR for root
  ansible.builtin.lineinfile:
    path: "/root/.bashrc"
    state: present
    line: 'export EDITOR=vim'
  when: ansible_os_family != "Alpine"
- name: Add alias to nobc
  ansible.builtin.lineinfile:
    path: "/root/.bashrc"
    state: present
    line: 'alias nobc=~sacha/bin/nobc'
  when: ansible_os_family != "Alpine"
