---
- name: Install pip3
  community.general.apk:
    name: py3-pip
    state: present
    update_cache: true
- name: Install mailrise pip3 packages
  ansible.builtin.pip:
    name: mailrise
- name: Copy mailrise config
  ansible.builtin.copy:
    src: "mailrise.conf"
    dest: /etc/mailrise.conf
    owner: root
    group: root
    mode: "0644"
- name: Copy mailrise startup script
  ansible.builtin.copy:
    src: "mailrise.rc"
    dest: /etc/init.d/mailrise
    owner: root
    group: root
    mode: "0744"
- name: Start mailrise
  ansible.builtin.service:
    name: mailrise
    state: started
