---
- name: Install pip3
  ansible.builtin.apt:
    name:
      - python3-pip
<<<<<<< HEAD
    state: latest
=======
    state: present
>>>>>>> 2ddc6f6839a2841fada385fc6846b101d2b25955
    update_cache: true
- name: Install mailrise pip3 packages
  ansible.builtin.pip:
    name: mailrise
- name: Copy mailrise config
  ansible.builtin.copy:
    src: "/mailrise.conf"
    dest: /etc/mailrise.conf
    owner: root
    group: root
    mode: "0644"
- name: Copy mailrise systemd script
  ansible.builtin.copy:
    src: "mailrise.systemd"
    dest: /etc/systemd/system/mailrise.service
    owner: root
    group: root
    mode: "0644"
- name: Stop postfix
  ansible.builtin.service:
    name: postfix
    state: stopped
- name: Start mailrise
  ansible.builtin.service:
    name: mailrise
    state: started
