---
dependencies: []

galaxy_info:
  role_name: noipv6
  author: sachapan
  description: Disable ipv6 via sysctl.
  company: "Krown"
  license: "MIT"
  min_ansible_version: 2.10
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - ipv6
