#      ansible.builtin.import_playbook: ssh.yml 
handlers:
  - name: Restart sshd
    ansible.builtin.service:
      name: sshd
      state: reloaded
  - name: Restart postfix
    ansible.builtin.service:
      name: postfix
      state: reloaded
