---
user:
  name: sacha
  ID: 501
  shell: /bin/zsh
  groups:
    - users
config_dirs:
  - { dir: ".config", mode: "0750" }
  - { dir: ".ssh", mode: "0700" }
  - { dir: ".vim", mode: "0750" }
  - { dir: ".vim/autoload", mode: "0750" }
  - { dir: ".vim/bundle", mode: "0750" }
config_files:
  - {
    src: "~/.config/telegram-send.conf",
    dest: "$HOME/.config/telegram-send.conf",
    mode: "0600",
  }
  - { src: "../files/ssh_config", dest: "$HOME/.ssh/config", mode: "0600" }
  - {
    src: "~/.ssh/id_rsa_github2",
    dest: "$HOME/.ssh/id_rsa_github2",
    mode: "0600",
  }
  - {
    src: "~/.ssh/id_rsa_gitea.pub",
    dest: "$HOME/.ssh/id_rsa_gitea.pub",
    mode: "0600",
  }
  - {
    src: "~/.ssh/id_rsa_gitea",
    dest: "$HOME/.ssh/id_rsa_gitea",
    mode: "0600",
  }
  - { src: "~/.ssh/id_rsa", dest: "$HOME/.ssh/id_rsa", mode: "0600" }
  - { src: "~/.ssh/known_hosts", dest: "$HOME/.ssh/known_hosts", mode: "0600" }
  # - {src: "../files/.gitconfig", dest: "$HOME/.gitconfig", mode: "0600" }
  - {
    src: "~/.ssh/authorized_keys",
    dest: "$HOME/.ssh/authorized_keys",
    mode: "0600",
  }
  - { src: "~/.vim/autoload", dest: "$HOME/.vim/", mode: "0600" }

copy_local_key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
