---
- hosts: localhost
  become: yes
  become_user: root
  become_method: sudo
  vars:
    homebrew_upgrade_all_packages: yes
  tasks:
  - name: Upgrade all homebrew packages (if configured).
    homebrew: update_homebrew=yes upgrade_all=yes
#    when: homebrew_upgrade_all_packages
