---
- hosts: all
  gather_facts: no  # Optional: reduce fact gathering for efficiency
  become: true
  tasks:
    - name: Verify sysctl setting for net.ipv6.conf.all.disable_ipv6
      ansible.builtin.command: "sysctl net.ipv6.conf.all.disable_ipv6"
      register: sysctl_output

    - name: Display the sysctl output
      debug:
        msg: "Sysctl output: {{ sysctl_output.stdout }}"

    - name: Check if IPv6 is disabled
      assert:
        that: sysctl_output.stdout | trim == 1
        msg: "net.ipv6.conf.all.disable_ipv6 is NOT set to 1"
