---
- hosts: all
#- import_playbook: tasks/initial.yml  
- import_playbook: tasks/apt_initial_packages.yml
  when: ansible_os_family == "Debian"
- import_playbook: tasks/dnf_initial_packages.yml
  when ansible_os_family == "RedHat"
# Add my_home next
- import_playbook: tasks/timezone.yml
  # when: ansible_os_family == "Debian"
- import_playbook: tasks/pip.yml
