---
- hosts: all
  gather_facts: True
- import_playbook: tasks/apt-initial-packages.yml
  when: ansible_os_family == "Debian"
- import_playbook: tasks/dnf-initial-packages.yml
  when: ansible_os_family == "Redhat"
- import_playbook: tasks/timezone.yml
- import_playbook: tasks/pip.yml
