---
- hosts: all
  gather_facts: True
- import_playbook: tasks/timezone.yml
  when: ansible_os_family == "Debian"
- import_playbook: tasks/pip.yml
  when: ansible_os_family == "Debian"
- import_playbook: tasks/apt-initial-packages.yml
  when: ansible_os_family == "Debian"
- import_playbook: tasks/apk-initial-packages.yml
  when: ansible_os_family == "Alpine"
#- import_playbook: tasks/apk
#  when: ansible_lsb_id == 'Ubuntu'
- import_playbook: tasks/dnf-initial-packages.yml
  when: ansible_os_family == "Redhat"
#- import_playbook: tasks/initial.yml
- import_playbook: tasks/myuser.yml
- import_playbook: tasks/myhome.yml
- import_playbook: tasks/disable_root_sshd_pass.yml
