---
- hosts: all
  become: true
  #vars_files:
  #  - ../vars/main.yml
  tasks:
    - name: Create my user account
      user:
        name: "{{ user.name }}"
        uid: "{{ user.ID }}"
        state: present
        password_lock: no
        password: "*"
        groups: "{{ user.groups }}"
        append: true
        create_home: true
        shell: "{{ user.shell }}"
    - name: Check if groups exist
      shell: /usr/bin/getent group | awk -F":" '{print $1}'
      register: etc_groups
    - name: Add user to existing secondary groups
      user: name="{{  user.name  }}" groups="{{  item  }}" append=yes
      #when: '"{{  item  }}" in etc_groups.stdout_lines'
      when: "item in etc_groups.stdout_lines"
      with_items:
        - sudo
        - wheel
        - docker
    - name: Set authorized key for my user
      ansible.builtin.authorized_key:
        user: "{{ user.name }}"
        state: present
        key: "{{ copy_local_key }}"
    - name: Grant my user sudo privilege
      lineinfile:
        path: "/etc/sudoers.d/{{ user.name }}"
        line: "{{ user.name }} ALL=(ALL) NOPASSWD: ALL"
        state: present
        create: "yes"
        owner: root
        group: root
        mode: 0440
