---
- hosts: rasps
  become: yes
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker
    docker_install_compose: true
    docker_users:
      - sacha
  # name: "Install docker"
  roles:
    - geerlingguy.pip
    - geerlingguy.docker_arm
