---
- hosts: ubuntu
  become: yes
  become_user: root
  become_method: sudo
#  sudo: True
  tasks:
   - name: updates a server
     apt: update_cache=yes
   - name: upgrade a server
     apt: upgrade=dist

