---
- hosts: ubuntu
  become: yes
  tasks:
    - name: dns setting
      lineinfile:
        path: "/etc/network/interfaces"
        state: present
        line: '        dns-nameservers 10.0.0.5 10.0.0.4 8.8.8.8'
