---
- hosts: ubuntu
  become: yes
  become_user: root
  become_method: sudo
#  sudo: True
  tasks:
   - name: dns-nameservers setting
     lineinfile: dest=/etc/network/interfaces line="        dns-nameservers 10.0.0.4 8.8.8.8"

