---
# Initial system setup on debian and alpine based systems
# sachapan@gmail.com
- hosts: all
  become: true
  vars_files:
    - ../vars/main.yml
  tasks:
    - name: Update apt
      apt: update_cache=yes state=latest
      changed_when: false
      when: ansible_os_family == "Debian"
    - name: Install required system packages on Debian
      apt: name={{ sys_packages_debian }} state=latest
      when: ansible_os_family == "Debian"
    - name: Update apk
      apk: update_cache=yes state=latest
      changed_when: false
      when: ansible_os_family == "Alpine"
    - name: Install required system packages on Alpine
      apk: name={{ sys_packages_alpine }} state=latest
      when: ansible_os_family == "Alpine"
    - name: Create my user account
      user:
        name: "{{ user.name }}"
        uid: "{{ user.ID }}"
        state: present
        groups: "{{ user.groups }}"
        append: true
        create_home: true
        shell: "{{ user.shell }}"
    - name: Set authorized key for my user
      authorized_key:
        user: "{{ user.name }}"
        state: present
        key: "{{ copy_local_key }}"
    - name: Grant my user sudo privilege
      lineinfile:
        path: "/etc/sudoers.d/{{ user.name }}"
        line: '{{ user.name }} ALL=(ALL) PASSED: ALL'
        state: present
        create: "yes"
        owner: root
        group: root
        mode: 0440
    - name: Disable ssh password authentication for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'
