---
# Initial system setup on debian based systems
# sachapan@gmail.com
- hosts: all
  become: true
  vars_files: 
    - ../vars/main.yml
  tasks:
    #- name: Install Prerequisites
    #  apt: name=aptitude update_cache=yes state=latest force_apt_get=yes
    - name: Update apt
      apt: update_cache=yes state=latest
      changed_when: False
      when: ansible_os_family == "Debian"
    - name: Install required system packages
      apt: name={{ sys_packages }} state=latest
      when: ansible_os_family == "Debian"
    - name: Create a new user
      user:
        name: "{{ user.name }}"
        uid: "{{ user.ID }}"
        state: present
        groups: "{{ user.groups }}"
        append: true
        create_home: true
        shell: "{{ user.shell }}"
    - name: Set authorized key for remote user
      authorized_key:
        user: "{{ user.name }}"
        state: present
        key: "{{ copy_local_key }}"
    - name: Grant user sudo privilege
      lineinfile:
        path: "/etc/sudoers.d/{{ user.name }}"
        line: '{{ user.name }} ALL=(ALL) NOPASSWD: ALL'
        state: present
        create: "yes"
        owner: root
        group: root
        mode: 0440
    - name: Disable password authentication for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'
