---
# Initial system setup on debian based systems
# sachapan@gmail.com
- hosts: all
  become: true
  vars:
    user:
      name: sacha
      ID: 501
      shell: /bin/zsh
    copy_local_key: "{{ lookup('file', lookup('env','HOME')+'/.ssh/id_rsa.pub') }}"
    sys_packages:
      - curl
      - vim
      - git
      - zsh
      - htop
      - tmux
      - file
      - speedtest-cli
      # - ansible
      # - ansible-lint
      # - docker-ce
      #- docker-compose
      #- python3-docker
      - python3-pip
      - fonts-powerline
      - neofetch
  tasks:
    - name: Timezone set to Toronto
      file:
        src: "/usr/share/zoneinfo/America/Toronto"
        dest: "/etc/localtime"
        state: link
    - name: Install Prerequisites
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes
    # Install Packages
    - name: Update apt
      apt: update_cache=yes
    - name: Install required system packages
      apt: name={{ sys_packages }} state=latest
    # User + Key Setup
    - name: Create a new user
      user:
        name: "{{ user.name }}"
        uid: "{{ user.ID }}"
        state: present
        group: users
        #groups: docker
        append: true
        create_home: true
        shell: "{{ user.shell }}"
    - name: Set authorized key for remote user
      authorized_key:
        user: "{{ user.name }}"
        state: present
        key: "{{ copy_local_key }}"
    # Sudo setup
    - name: Grant user sudo privilege
      lineinfile:
        path: "/etc/sudoers.d/{{ user.name }}"
        line: '{{ user.name }} ALL=(ALL) NOPASSWD: ALL'
        state: present
        create: "yes"
        owner: root
        group: root
        mode: 0440
    # My dotfiles configuration
    # - name: Create initial dotfiles and pull from git
    # git clone some zsh custom plugins I like
    # - name: git clone .oh-my_zsh customizations
    #  git:
    #    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    #    dest: /home/sacha/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    # - name: Now change file ownership
    #  file:
    #    path: "/home/sacha/.oh-my-zsh"
    #    owner: "sacha"
    #    group: "users"
    #    recurse: yes
    # sshd configuration
    - name: Disable password authentication for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'
