---
- hosts: debian
  vars_files:
        - ../vars/main.yml
  remote_user: sacha
  tasks:
    - name: Ensure HOME/.config exists
      file:
        path: $HOME/.config
        state: directory
    - name: Copy $HOME files not under version control
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      loop: "{{ config_files }}"
    #- name: Copy ssh config
    #  copy:
    #    src: /home/sacha/.ssh/config
    #    dest: $HOME/.ssh/config
    #- name: Copy github key
    #  copy:
    #    src: /home/sacha/.ssh/id_rsa_github
    #    dest: $HOME/.ssh/id_rsa_github
    #    mode: "0600"
        # owner: "{{ remote_user }}"
   # - name: Remove oh-my-zsh directory
   #   file:
   #     path: ~/.oh-my-zsh
   #     state: absent
    - name: Clone oh-my-zsh
      git:
        repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
        dest: $HOME/.oh-my-zsh
        update: yes
        force: yes
    - name: Add zsh-autosuggestions to oh-my-zsh customizations
      git:
        repo: 'https://github.com/zsh-users/zsh-autosuggestions'
        dest: $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    - name: Add zsh-syntax-highlighting to oh-my-zsh customizations
      git:
        repo: 'https://github.com/zsh-users/zsh-syntax-highlighting'
        dest: $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    - name: Clone my dotfiles from git - First purge clone
      file:
        path: $HOME/.dotfiles.git
        state: absent
        # recurse: yes
    # - name: And now clone dotfiles into a bare repo
    #  command: "{{ dotfiles }} clone --bare https://github.com/sachapan/dotfiles.git $HOME/.dotfiles.git"
    - name: Clone my dotfiles into a bare repo
      git:
        repo: https://github.com/sachapan/dotfiles.git
        dest: '$HOME/.dotfiles.git'
        version: main
        bare: yes
        clone: yes
        update: yes
        force: yes
    - name: Remove default dotfiles
      file:
        path: "{{ item }}"
        state: absent
      loop: "{{ remove_files }}"
    - name: Don't show untracked files in this repo
      command: "{{ dotfiles }} config --local status.showUntrackedFiles no"
    - name: Drop in my preferred dotfiles from git
      command: "{{ dotfiles }} checkout"
