---
- hosts: all
  become: true
  vars:
    nfsmounts:
      - { path: "/mnt/Movies", src: "deathstar:/Movies" }
  tasks:
    - name: nfs-common installed
      apt: pkg=nfs-common state=latest

    - name: Mount Movies
      mount:
        fstype: nfs
        opts: defaults,rw,async
        dump: "0"
        passno: "0"
        state: mounted
        src: "deathstar:/Movies"
        path: "/mnt/Movies"
    - name: Mount Multimedia
      mount:
        fstype: nfs
        opts: defaults,rw,async
        dump: "0"
        passno: "0"
        state: mounted
        src: "deathstar:/Multimedia"
        path: "/mnt/Multimedia"
    - name: Mount TV Shows
      mount:
        fstype: nfs
        opts: defaults,rw,async
        dump: "0"
        passno: "0"
        state: mounted
        src: "deathstar:/TV Shows"
        path: "/mnt/TV"
 
