---
# Install pip3 apps
- hosts: all
  become: true
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: telegram-send
#      - name: python-venv
#      - name: python-telegram-send
      #- name: 2to3
      - name: pushbullet-cli
  roles:
    - geerlingguy.pip
