---
- hosts: all
  become: true
  vars_files:
    - ../vars/main.yml
  tasks:
    - name: Set TimeZone to "{{ time_zone }}"
      file:
        src: "/usr/share/zoneinfo/{{ time_zone }}"
        dest: "/etc/localtime"
        state: link
      when: ansible_os_family == "Debian"
