---

- name: ansible common setup
  hosts: ansible_managed
  gather_facts: true
  become: true
  remote_user: root
  vars_files:
    vars/main.yml
  tasks:
  - name: Configure ansible account - simba
    block:
    - name: Create user
      ansible.builtin.user:
        name: "{{ management_user.name}}"
        uid: "{{ management_user.UID }}"
        state: present
        password_lock: false
        password: "*"
        groups: "{{ management_user.groups }}"
        append: true
        create_home: true
        shell: "{{ management_user.shell }}"
