---

- name: ansible common setup
  hosts: ansible_managed
  gather_facts: true
  become: true
  remote_user: root
  vars_files:
    vars/main.yml
  tasks:
  - name: Configure ansible account
    block:
    - name: Create user
      ansible.builtin.user:
        name: "{{ management_user.name}}"
        uid: "{{ management_user.UID }}"
        state: present
        password_lock: false
        password: "*"
        groups: "{{ management_user.groups }}"
        append: true
        create_home: true
        shell: "{{ management_user.shell }}"
    - name: Grant ansible account sudo privilege
      ansible.builtin.lineinfile:
        path: "/etc/sudoers.d/{{ management_user.name }}"
        line: "{{ management_user.name }} ALL=(ALL) NOPASSWD: ALL"
        state: present
        create: "yes"
        owner: root
        group: root
        mode: "0440"
