---

- name: Initial system build and configuration.
  hosts: all
  gather_facts: true
  become: true
  remote_user: root
  vars_files:
    vars/main.yml
  tasks:
    - name: Install locales package
      ansible.builtin.package:
        name: "locales"
        state: latest
        update_cache: true
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: Set locale
      ansible.builtin.import_tasks:
        tasks/locale.yml
      tags: locale
      when: ansible_os_family != "Alpine"
    - name: Set timezone
      ansible.builtin.import_tasks:
        tasks/timezone.yml
    - name: Install preferred packages on Debian, Alpine systems.
      ansible.builtin.import_tasks: tasks/install-packages.yml
      tags: packages
      # ansible.builtin.package:
      #  name: "{{ packages[ansible_os_family | lower] }}"
      #  state: latest
      #  update_cache: true
    # Create ansible user
    # - name: Create ansible user
    # - name: Create monitoring user
    # Create monitoring user
    # - name: Setup my user
      # ansible.builtin.import_tasks: tasks/my-user.yml
    # - name: Setup my home sweet HOME
    #   ansible.builtin.import_tasks: tasks/my-home.yml
    #   become_user: "{{ user.name }}"
    #   tags: home
    # - name: Change some root defaults
    #   ansible.builtin.import_tasks: tasks/fix_root.yml
    #   tags: root
    - name: Fix ping permission on lxc containers.
      ansible.builtin.import_tasks: 
        tasks/fix_ping.yml
      when: ansible_virtualization_type == "lxc"
    - name: adjust journald config
      ansible.builtin.import_tasks: tasks/journald_limit.yml
      when: ansible_os_family != "Alpine"
#    - name: Disable ssh password login for root
#      ansible.builtin.include_tasks: tasks/disable_root_sshd_pass.yml
#    - name: Configure ssh
#      ansible.builtin.import_playbook: ssh.yml 
  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: reloaded
