---

- name: monitoring setup
  hosts: monitored
  gather_facts: true
  become: true
  remote_user: root
  vars_files:
    vars/main.yml
  tasks:
  - name: Configure monitoring account - roomba 
    block:
    - name: Create user
      ansible.builtin.user:
        name: "{{ monitoring_user.name}}"
        uid: "{{ monitoring_user.UID }}"
        state: present
        password_lock: false
        password: "*"
        groups: "{{ monitoring_user.groups }}"
        append: true
        create_home: true
        shell: "{{ monitoring_user.shell }}"
