---
user:
  name: sacha
  ID: 501
  shell: /bin/zsh
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
sys_packages: 
  - curl
  - vim
  - git
  - zsh
  - htop
  - tmux
  - file
  - speedtest-cli
  - python3-pip
  - fonts-powerline
  - neofetch
