---
#remote_user: sacha
user:
  name: sacha
  ID: 501
  shell: /bin/zsh
  groups: users
config_files:
  - { src: "../files/telegram-send.conf", dest: "$HOME/.config/telegram-send.conf", mode: "0600" }
  - { src: "../files/ssh_config", dest: "$HOME/.ssh/config", mode: "0600" }
  - { src: "../files/id_rsa_github", dest: "$HOME/.ssh/id_rsa_github", mode: "0600" }
  - { src: "../files/known_hosts", dest: "$HOME/.ssh/known_hosts", mode: "0600" }
  - { src: "../files/.gitconfig", dest: "$HOME/.gitconfig", mode: "0600" }
#
#copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa_github.pub') }}"
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
#copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa_github') }}"
sys_packages: 
  - curl
  - etckeeper
  - file
  - fonts-powerline
  - git
  - htop
  - neofetch
  - python3-pip
  - smartmontools
  - speedtest-cli
  - tmux
  - vim
  - yamllint
  - zsh
time_zone:  America/Toronto
dotfiles:  '/usr/bin/git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME'
remove_files:
  - .aliases
  - .bashrc
  - .gitconfig
  - .gvimrc
  - .minttyrc
  - .profile
  - .tmux.conf
  - .vim
  - .vimrc
  - .vimrc
  - .xscreensaver
  - .zshrc
