---
user:
  name: sacha
  ID: 501
  shell: /bin/zsh
  groups: users
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
sys_packages: 
  - curl
  - vim
  - git
  - zsh
  - htop
  - tmux
  - file
  - speedtest-cli
  - python3-pip
  - fonts-powerline
  - neofetch
  - etckeeper
  - yamllint
#  - telegram-cli
#  Needed to compile telegram-cli
#  - libreadline-dev
#  - libconfig-dev
#  - libssl-dev
#  - lua5.2
#  - liblua5.2-dev
#  - libevent-dev
#  - libjansson-dev
#  - libpython-dev
#  - libssl1.0-dev
#  - make
time_zone:  America/Toronto
