---
- name: Configure ansible management nodes
  hosts: ansible_hosts 
  gather_facts: true
  become: true
  vars_files:
    vars/main.yml
  tasks:
    - name: Call install task
      ansible.builtin.include_tasks: tasks/ans_controller.yml
    - name: Clone my ansible stuff
      ansible.builtin.include_tasks: tasks/clone_ansible.yml
    - name: Configure githooks
      ansible.builtin.copy:
        src: "files/ansible_git_config"
        dest: "$HOME/ansible/git"
      tags: ansible-git

