# TODO Currently assumes node_exporter has already been installed - BAD
# install required packages
# moreutils, update-notifier-common
# install node-exporter
# copy apt-metrics.sh to /usr/share/
# install apt hook to /etc/apt/apt.conf.d
#  to send output to /var/lib/node_exporter/textfile_collector
# configure node-exporter systemd startup file to query file /var/lib/node_exporter/textfile_collector
#
---
- name: Install apt package status monitoring for node_exporter ingestion
  hosts: node_exporter
  become: true
  vars_files:
    vars/main.yml
  handlers:
    - name: restart_node_exporter
      ansible.builtin.service:
        name: node_exporter
        state: restarted
  tasks:
    - name: "Remove EXTERNALLY_MANAGED python config file on bookworm."
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/usr/lib/python3/EXTERNALLY-MANAGED"
        - "/usr/lib/python3.11/EXTERNALLY-MANAGED"
        - "/usr/lib/python3.12/EXTERNALLY-MANAGED"
          #- name: Ensure pip is installed
          #  ansible.builtin.apt:
          #    name: 
          #      - python3-pip
          #    update_cache: true
      when: ansible_distribution == 'Debian' 
    - name: Install required packages on Debian
      ansible.builtin.apt:
        name:
          - python3-pip
          - moreutils
          - apt-config-auto-update
        update_cache: true
      when: ansible_distribution == "Debian"
    - name: Install required packages on Ubuntu
      ansible.builtin.apt:
        name:
          - moreutils
            #- update-notifier-common
          - apt-config-auto-update
      when: ansible_distribution == "Ubuntu"
    - name: Install prometheus_client with pip
      ansible.builtin.pip:
        name: 
          - prometheus_client
    - name: Install apt-info script
      ansible.builtin.copy:
        src: "files/apt-info"
        dest: "/usr/local/bin/apt-info"
        mode: '0755'
    - name: Ensure stats collection directory exists
      ansible.builtin.file:
        path: /var/log/proms
        state: directory
        mode: '0755'
    - name: Custom auto-update config file
      ansible.builtin.copy:
        src: "files/apt.conf.d_10periodic"
        dest: "/etc/apt/apt.conf.d/10periodic"
    - name: Export package list on apt update
      ansible.builtin.copy:
        src: "files/apt.conf.d_60prometheus-metrics"
        dest: "/etc/apt/apt.conf.d/60prometheus-metrics"
    - name: Ensure node_exporter will monitor for apt info prom file
      ansible.builtin.copy:
        src: "files/node_exporter.service-filecollector"
        dest: "/etc/systemd/system/node_exporter.service"
          #notify:
          #- restart_node_exporter
    - name: Restart node_exporter
      ansible.builtin.service:
        name: node_exporter
        state: restarted
        daemon_reload: true
    - name: Update apt package listing
      ansible.builtin.apt:
        update_cache: true

