---
- name: Configure mail
  hosts: all
  gather_facts: true
  become: true
  remote_user: root
  vars_files:
    vars/main.yml
  tasks:
    - name: Install mail system packages
      ansible.builtin.package:
        state: latest
        update_cache: true
      with_items:
        - postfix
        - mailutils
      changed_when: false
    - name: Copy postfix main.cf 
      ansible.builtin.copy:
        src: "files/postfix/main.cf"
        dest: "/etc/postfix/main.cf"
      notify:
        - Restart postfix 
  handlers:
    - name: Restart postfix
      ansible.builtin.service:
        name: postfix
        state: reloaded
