---

- name: disable ipv6
  hosts: all
  gather_facts: true
  become: true
  remote_user: root
  roles:
    - disable_ipv6
  #tasks:
  #- name: Check if ipv6 is currently disabled
  #  - name: Check if ipv6 settings are disabled in /etc/sysctl.conf
  #    ansible.builtin.lineinfile:
  #      path: "/etc/sysctl.conf"
  #      state: present
  #      line: "{{ item }}"
  #    with_items:
  #        - "net.ipv6.conf.all.disable_ipv6=1"
  #        - "net.ipv6.conf.default.disable_ipv6=1"
  #        - "net.ipv6.conf.lo.disable_ipv6=1"
  #  - name: Apply configuration
  #    ansible.builtin.shell: sysctl -p
  #- name: Check that ipv6 is disabled

      #cat /proc/sys/net/ipv6/conf/all/disable_ipv6
