---
- name: Fix ping permission on lxc containers.
  hosts: containers
  ignore_unreachable: true
  gather_facts: true
  remote_user: sacha
  tasks:
    - name: Is this an lxc container
      ignore_errors: true
      #when: ansible_virtualization_type == "lxc"
      block:
        - name: Check if ping fails for my user
          ansible.builtin.shell: ping -c 1 localhost
          ignore_errors: true
          changed_when: false
          register: pingperm
            #- debug: var=pingperm.stderr_lines
            #- debug: var=pingperm.stdout_lines
        - name: Change permissions if needed
          become: true
          become_user: root
          ansible.builtin.shell: setcap cap_net_raw+p /bin/ping
          when: pingperm.stderr_lines is search("Operation not permitted")
      when: ansible_virtualization_type is search("lxc")

