---
- hosts: all
  name: Initial system build and configuration.
  gather_facts: true
  become: true
  vars_files:
    vars/main.yml
  tasks:
    - name: Set locale
      ansible.builtin.import_tasks:
        tasks/locale.yml
    - name: Set timezone
      ansible.builtin.import_tasks:
        tasks/timezone.yml
    - name: Enable epel-release repo on Rocky
      ansible.builtin.package:
        name: epel-release
        state: present
      when: ansible_os_family == "Rocky"
    - name: Install preferred packages on Debian, Alpine
            and RedHat based systems.
      ansible.builtin.import_tasks: tasks/install-packages.yml
      # ansible.builtin.package:
      #  name: "{{ packages[ansible_os_family | lower] }}"
      #  state: latest
      #  update_cache: true
    - name: Disable ssh password login for root
      ansible.builtin.import_tasks: tasks/disable_root_sshd_pass.yml
    - name: Call notifiers task book
      ansible.builtin.import_tasks: tasks/notifiers.yml
      tags: notifiers
    - name: Setup my user
      ansible.builtin.import_tasks: tasks/my-user.yml
    - name: Setup my home sweet HOME
      ansible.builtin.import_tasks: tasks/my-home.yml
      become_user: "{{ user.name }}"
      tags: home
