---
- name: Install Docker
  hosts: docker_hosts
  become: true
  vars_files:
    vars/main.yml
  tasks:
    - name: Reset ansible_distribution on LMDE
      ansible.builtin.set_fact:
        ansible_distribution: "Debian"
      when: ansible_distribution == "LMDE"
    - name: Show new ansible_distribution
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }}"
    - name: Reset ansible_distribution_release on LMDE
      ansible.builtin.set_fact:
        ansible_distribution_release: "bookworm"
      when: ansible_distribution_release == "faye"
     
    - name: Install apt-transport-https
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
        state: latest
        update_cache: true

    - name: Add signing key and repository
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present
          #      ansible.builtin.deb822_repository:
          #        name: docker
          #        types: [deb]
          #        uris: "https://download.docker.com/linux/"
          #        components: [binary]
          #        state: present
          #        enabled: true
          #          #  "{{ ansible_distribution | lower }}/gpg"
          #dest: /etc/apt/trusted.gpg.d/docker.asc
          #mode: '0644'
    - name: Remove default docker repository
      ansible.builtin.file:
        path: /etc/apt/sources.d/docker.list
        state: absent
    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        filename: docker
        # repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        repo: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable"
        state: present
    - name: Install Docker
      ansible.builtin.apt:
        name:
          # - docker
          # - docker.io
          - docker-ce
          - docker-compose
          - docker-registry
        state: latest
        update_cache: true

    - name: Start Docker engine
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add my user to docker group
      ansible.builtin.user:
        name: "{{ user.name }}"
        groups: docker
        append: true
    - name: Do my docker things
      ansible.builtin.import_tasks: tasks/my-docker.yml
      tags: my-docker
