---
- hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Set timezone.
      import_tasks: tasks/timezone.yml
      when: ansible_os_family == "Debian"
    - name: Install Debian packages.
      import_tasks: tasks/apt-initial-packages.yml
      when: ansible_os_family == "Debian"
    - name: Install Alpine packages.
      import_tasks: tasks/apk-initial-packages.yml
      when: ansible_os_family == "Alpine"
    - name: Install Redhat packages.
      import_tasks: tasks/dnf-initial-packages.yml
      when: ansible_os_family == "Redhat"
    - name: Disable ssh password login for root.
      import_tasks: tasks/disable_root_sshd_pass.yml
    - name: Install telegram and pushbullet.
      roles:
        - geerlingguy.pip
      when: ansible_os_family == "Debian"
    - name: Setup my user.
      import_tasks: tasks/my-user.yml
    - name: Setup my home sweet HOME.
      import_playbook: my-home.yml
