---

- name: mysqld-exporter installation
  hosts: mysqld_nodes
  gather_facts: true
  become: true
  vars_files:
    vars/mysqld_exporter.yml
  tasks:
    - name: Create mysqld_exporter cert dir
      ansible.builtin.file:
        path: "{{ dir }}"
        state: directory
        owner: root
        group: root
    - name: Create certificate and key
      community.crypto.x509_certificate:
        path: "{{ cert_file  }}"
        csr_path: "{{ csr_file }}"
        privatekey_path: "{{ key_file }}"
        provider: selfsigned
  collections:
    - prometheus.prometheus
  roles:
    - prometheus.prometheus.mysqld_exporter
