---
- hosts: all
  become: true
  name: Install notifiers.
  tasks:
    - name: "Install telegram."
      ansible.builtin.pip:
        name: telegram-send
    - name: "Install pushbullet."
      ansible.builtin.pip:
        name: pushbullet-cli
