---
- name: Upgrade alpine hosts
  hosts: alpine
  become: yes
  tasks:
    - name: update package cache and install all updates
      ansible.builtin.apk:
        update_cache: yes
        upgrade: true
        state: "latest"
