---
- name: Upgrade debian hosts
  hosts: debian
  become: yes
  tasks:
  - name: Update cache and upgrade all installed packages
    ansible.builtin.apt:
      upgrade: yes
      update_cache: yes
      clean: yes
      cache_valid_time: 86400 #one day

