---
- name: Upgrade debian hosts
  hosts: all
  become: yes
  tasks:
  - name: Apply all patches, update cache and autoremove defunct packages
    ansible.builtin.import_tasks:
      tasks/debian-patch.yml
    when: ansible_facts['distribution'] == 'Debian'

