---
- hosts: postfixclients
  become: true
  vars_files:
    vars/main.yml
  tasks:
    - name: Install apps
      ansible.builtin.package:
        name: postfix
        state: latest
        update_cache: true
    - name: Remove default blank relay
      ansible.builtin.lineinfile:
        path: "/etc/postfix/main.cf"
        state: absent
        line: "relayhost ="
    - name: set relay to razor
      ansible.builtin.lineinfile:
        path: "/etc/postfix/main.cf"
        state: present
        line: "{{ item }}"
      with_items:
        - "relayhost = razor.lan"
    - name: restart postfix
      ansible.builtin.service:
        name: postfix
        state: restarted 
