---
- hosts: proxmox
  user: root
  tasks:
  - name: Remove no valid sub popup
    ansible.builtin.replace:
      path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
        #path: "{{ proxmoxlib_path }}"
      regexp: >-
         (^\s+)(Ext.Msg.show\(\{\s+title:\s+gettext\('No valid subscription)
      replace: '\1void({ //\2'
      backup: yes
