---
- hosts: proxmox_cluster
  vars_files:
    vars/proxmox.yml
  vars_prompt:
    - name: vmid
      prompt: Virtual machine ID to stop
      private: no
  user: root
  serial: 1
  tasks:
  - name: Stop a vm instance
    community.general.proxmox_kvm:
      api_user: "{{ proxmox_api_user }}"
      api_host: "{{ proxmox_api_host }}"
      api_token_id: "{{ proxmox_api_token_id }}"
      api_token_secret: "{{ proxmox_api_token_secret }}"
      vmid: "{{ vmid }}"
      state: stopped
      node: pve2

