---
- hosts: qemu_guests
  become: true
  vars_files:
    vars/qemu-agent.yml
  tasks:
    - name: Install qemu agent
      ansible.builtin.import_tasks: tasks/qemu-agent.yml

        #---
        #- name: Install qemu-guest-agent package
        #  hosts: all
        #  become: true
        #  become_method: ansible.builtin.sudo
        #
        #  tasks:
        #    - name: Install qemu-guest-agent
        #      ansible.builtin.apt:
        #        name: qemu-guest-agent
        #        state: present
