---
# tasks file for my-user
- name: Configure my user account
  block:
    - name: Create user
      ansible.builtin.user:
        name: "{{ user.name }}"
        uid: "{{ user.ID }}"
        state: present
        password_lock: false
        password: "*"
        groups: "{{ user.groups }}"
        append: true
        create_home: true
        shell: "{{ user.shell }}"
    - name: Check if groups exist
      ansible.builtin.shell:
        cmd: set -o pipefail && /usr/bin/getent group | awk -F":" '{print $1}'
        executable: /bin/bash
      changed_when: false
      register: etc_groups
    - name: Add user to existing secondary groups
      ansible.builtin.user:
        name: "{{ user.name }}"
        groups: "{{ item }}"
        append: true
      when: "item in etc_groups.stdout_lines"
      with_items:
        - sudo
        - wheel
        - docker
#    - name: Set authorized key for my user
#      ansible.posix.authorized_key:
#        user: "{{ user.name }}"
#        state: present
#        key: "{{ copy_local_key }}"
    - name: Grant my user sudo privilege
      ansible.builtin.lineinfile:
        path: "/etc/sudoers.d/{{ user.name }}"
        line: "{{ user.name }} ALL=(ALL) NOPASSWD: ALL"
        state: present
        create: "yes"
        owner: root
        group: root
        mode: "0440"
